# Generated by Django 3.2.4 on 2021-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(default=-1)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product/images')),
            ],
        ),
    ]
