# Generated by Django 3.2.4 on 2021-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=-1)),
                ('product_id', models.IntegerField(default=-1)),
                ('qty', models.IntegerField(default=-1)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
